name: Deploy Frontend by Cloudfront

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install Dependencies
        run: npm install

      - name: Set environment variables for Develop
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL_DEV }}" > .env
        env:
          REACT_APP_ENV: development

      - name: Build Project for Develop
        if: github.ref == 'refs/heads/dev'
        run: npm run build:dev

      - name: Set environment variables for Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL_PROD }}" > .env
        env:
          REACT_APP_ENV: production

      - name: Build Project for Production
        if: github.ref == 'refs/heads/main'
        run: npm run build:prod

      - name: Invalidate CloudFront Cache for Develop
        if: github.ref == 'refs/heads/dev'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }} --paths "/*"

      - name: Invalidate CloudFront Cache for Production
        if: github.ref == 'refs/heads/main'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} --paths "/*"
