name: Deploy Frontend by Cloudfront

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Ensure env-cmd is installed
        run: npm install env-cmd --save-dev

      - name: Build Project for Develop
        if: github.ref == 'refs/heads/dev'
        run: npm run build:dev

      - name: Build Project for Production
        if: github.ref == 'refs/heads/main'
        run: npm run build:prod

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3 for Develop
        if: github.ref == 'refs/heads/dev'
        run: aws s3 sync build s3://ustock-dev-bucket/react/ --delete

      - name: Deploy to S3 for Production
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync build s3://ustock-bucket/react/ --delete

      - name: Invalidate CloudFront Cache for Develop
        if: github.ref == 'refs/heads/dev'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }} --paths "/*"

      - name: Invalidate CloudFront Cache for Production
        if: github.ref == 'refs/heads/main'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} --paths "/*"
